---

stages:
  - build:theme
  - build
  - deploy

build:theme:
  stage: build:theme
  image: node:17.2.0-slim
  script:
    - cd "${CI_PROJECT_DIR}/themes/ght1pc9kc"
    - npm install --unsafe-perm
    - npx tailwindcss -i src/syntax.css -o static/syntax.css --minify
    - npx tailwindcss -i src/main.css -o static/main.css --minify
  cache:
    untracked: true
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/themes/ght1pc9kc

build:pages:
  stage: build
  image: registry.gitlab.com/pages/hugo/hugo_extended:0.89.4
  dependencies:
    - build:theme
  script:
    - hugo --minify
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  dependencies:
    - build:pages
  script:
    - find public -type f -iregex '.*\.\(htm\|html\|txt\|text\|js\|css\|json\)$' -execdir gzip -f --keep {} \;
  artifacts:
    paths:
      - public
  only:
    - master
