variables:
  GULP_VERSION: "3.9.1"
  HUGO_VERSION: "0.57"

stages:
  - build:theme
  - build
  - deploy

build:theme:
  stage: build:theme
  image: node:12.13.1-slim
  before_script:
    - npm -g install gulp@${GULP_VERSION}
  script:
    - cd "${CI_PROJECT_DIR}/themes/ght1pc9kc"
    - npm install --unsafe-perm
    - gulp prod
  cache:
    untracked: true
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/themes/ght1pc9kc

build:pages:
  stage: build
  image: monachus/hugo:v0.58.3
  dependencies:
    - build:theme
  script:
    - hugo
  artifacts:
    paths:
     - public

pages:
  stage: deploy
  dependencies:
    - build:pages
  script:
    - find public -type f -iregex '.*\.\(htm\|html\|txt\|text\|js\|css\|json\)$' -execdir gzip -f --keep {} \;
  artifacts:
    paths:
    - public
  only:
  - master