baseURL = "https://blog.ght1pc9kc.fr"
languageCode = "fr-fr"
title = "j’ai acheté un PC..."
theme = "ght1pc9kc"
uglyurls = true
pygmentsUseClasses = true
pygmentsCodeFences = true

[permalinks]
  blog = "/:year/:title"