baseURL = "https://blog.ght1pc9kc.fr"
languageCode = "fr-fr"
title = "j’ai acheté un PC..."
theme = "ght1pc9kc"
uglyurls = true
pygmentsUseClasses = true
pygmentsCodeFences = true
googleAnalytics = "UA-67836375-1"

[params]
  mixpanel = "50791435686447e860177b666f803ec1"


[permalinks]
  blog = "/:year/:title"

[markup.goldmark.renderer]
  unsafe= true