baseURL = "https://blog.ght1pc9kc.fr"
languageCode = "fr-fr"
title = "j’ai acheté un PC..."
theme = "ght1pc9kc"
uglyurls = true
pygmentsUseClasses = true
pygmentsCodeFences = true
#googleAnalytics = "UA-67836375-1"

[permalinks]
  blog = "/:year/:slug"

[markup.goldmark.renderer]
  unsafe= true